[package]
name = "user_profile"
version = "1.0.0"
authors = []

[addresses]
user_profile = "0xf472a9735febdf619040db29e4f564e77ac5fbc6ea829d7f9cd9563fc8743b8d"
giftcards_addr = "0xf472a9735febdf619040db29e4f564e77ac5fbc6ea829d7f9cd9563fc8743b8d"

[dev-addresses]

[dependencies.AptosFramework]
local = "./local_deps/aptos-core/aptos-move/framework/aptos-framework"

[dev-dependencies]
